FROM node:18-alpine

WORKDIR /app

# Copy root package files
COPY package.json package-lock.json ./

# Copy frontend package files
COPY packages/frontend ./packages/frontend

# Install dependencies
RUN npm install

# Development mode
EXPOSE 5173

CMD ["npm", "run", "--workspace=packages/frontend", "dev", "--", "--host"]
